Repository apache/incubator-seata-go, pull requests merged in 2022-12, with the labels that each got.

#333 feature:build undo log by insert target SQL
  pkg/datasource/sql/types/meta.go
  pkg/datasource/sql/types/meta_test.go
  pkg/datasource/sql/undo/builder/mysql_insert_undo_log_builder.go
  pkg/datasource/sql/undo/builder/mysql_insert_undo_log_builder_test.go
Labels: coding

#387 fix: loop recursion problem in OpenConnector
  pkg/datasource/sql/driver.go
Labels: coding

#383 add tcc fence config logic
  go.mod
  pkg/client/client.go
  pkg/client/config.go
  pkg/client/config_test.go
  pkg/client/rm_client.go
  pkg/rm/tcc/fence/fence.go
  pkg/rm/tcc/tcc.go
  testdata/conf/seatago.yml
Labels: coding, rm, tm

#392 optimize some format
  pkg/datasource/sql/conn.go
  pkg/datasource/sql/conn_at.go
  pkg/datasource/sql/conn_at_test.go
  pkg/datasource/sql/conn_xa.go
  pkg/datasource/sql/conn_xa_test.go
  pkg/datasource/sql/connector.go
  pkg/datasource/sql/connector_test.go
  pkg/datasource/sql/driver.go
  pkg/datasource/sql/exec/executor.go
  pkg/datasource/sql/exec/hook.go
  pkg/datasource/sql/exec/xa/executor_xa.go
  pkg/datasource/sql/stmt.go
  pkg/datasource/sql/tx.go
  pkg/datasource/sql/tx_at.go
  pkg/datasource/sql/tx_xa.go
  pkg/datasource/sql/types/executor.go
  pkg/datasource/sql/types/types.go
Labels: coding

#394 optimize at base executor
  pkg/datasource/sql/conn_test.go
  pkg/datasource/sql/exec/at/executor_at.go
  pkg/datasource/sql/exec/executor.go
  sample/at/basic/main.go
  sample/at/gin/client/main.go
  sample/at/rollback/client/main.go
  sample/at/rollback/server/main.go
  sample/at/rollback/server2/main.go
Labels: coding, sample

#398 feat(pkg/client,pkg/config):tm config
  pkg/client/config.go
  pkg/client/config_test.go
  pkg/datasource/sql/undo/builder/mysql_insert_undo_log_builder.go
  pkg/tm/config.go
  testdata/conf/seatago.yml
Labels: coding, tm

#401 fix branch register response
  pkg/rm/rm_remoting.go
Labels: coding, rm

#400 optimize protocol init
  pkg/protocol/codec/branch_commit_req_codec.go
  pkg/protocol/codec/branch_commit_response_codec.go
  pkg/protocol/codec/branch_register_req_codec.go
  pkg/protocol/codec/branch_register_response_codec.go
  pkg/protocol/codec/branch_report_req_codec.go
  pkg/protocol/codec/branch_rollback_req_codec.go
  pkg/protocol/codec/branch_rollback_response_codec.go
  pkg/protocol/codec/branch_statue_report_response_codec.go
  pkg/protocol/codec/codec.go
  pkg/protocol/codec/global_begin_request_codec.go
  pkg/protocol/codec/global_begin_response_codec.go
  pkg/protocol/codec/global_commit_req_codec.go
  pkg/protocol/codec/global_commit_response_codec.go
  pkg/protocol/codec/global_report_response_codec.go
  pkg/protocol/codec/global_rollback_req_codec.go
  pkg/protocol/codec/global_rollback_response_codec.go
  pkg/protocol/codec/global_status_req_codec.go
  pkg/protocol/codec/global_status_response_codec.go
  pkg/protocol/codec/register_rm_request_codec.go
  pkg/protocol/codec/register_rm_response_codec.go
  pkg/protocol/codec/register_tm_request_codec.go
  pkg/protocol/codec/register_tm_response_codec.go
  pkg/remoting/getty/getty_client_test.go
  pkg/remoting/getty/rpc_client.go
Labels: coding, protocol, remoting

#380 feat: support xa mysql connection
  pkg/datasource/sql/conn_at_test.go
  pkg/datasource/sql/conn_xa_test.go
  pkg/datasource/sql/exec/mysql_xa_resource.go
  pkg/datasource/sql/exec/mysql_xa_resource_test.go
  pkg/datasource/sql/exec/resource_xa.go
Labels: coding

#389 Feat xa branch xid
  go.mod
  go.sum
  pkg/datasource/sql/xa/xa_branch_xid.go
  pkg/datasource/sql/xa/xa_branch_xid_test.go
  pkg/datasource/sql/xa/xa_xid.go
  pkg/datasource/sql/xa/xa_xid_builder.go
Labels: coding

#405 [AT] add insert on duplicate
  pkg/datasource/sql/datasource/mysql/trigger.go
  pkg/datasource/sql/types/meta.go
  pkg/datasource/sql/undo/builder/mysql_insertonduplicate_update_undo_log_builder.go
  pkg/datasource/sql/undo/builder/mysql_insertonduplicate_update_undo_log_builder_test.go
Labels: coding

#408 optimize log init
  pkg/client/client.go
  pkg/datasource/sql/undo/builder/mysql_delete_undo_log_builder_test.go
  pkg/remoting/getty/getty_client_test.go
  pkg/remoting/processor/client/client_heart_beat_processor_test.go
  pkg/rm/tcc/fence/fence_api_test.go
  pkg/rm/tcc/tcc_service_test.go
  pkg/tm/global_transaction_test.go
  pkg/util/log/logging.go
  sample/at/non_transaction/main.go
  sample/at/non_transaction/service.go
Labels: coding, sample, remoting, rm, tm

#406 add transport config
  conf/config.yaml
  conf/seata_config.yml
  pkg/client/config.go
  pkg/client/config_test.go
  pkg/config/seata_config_test.go
  pkg/datasource/sql/exec/at/delete_executor.go
  pkg/datasource/sql/exec/at/insert_executor.go
  pkg/remoting/getty/config.go
  testdata/conf/seatago.yml
Labels: coding, remoting, config

#412 add RM config
  pkg/client/config.go
  pkg/client/config_test.go
  pkg/rm/config.go
Labels: coding, rm
