Repository apache/incubator-seata-go, pull requests merged in 2022-09, with the labels that each got.

#240 Feature add undo log manager delete
  go.mod
  go.sum
  pkg/common/util/slice_to_str.go
  pkg/constant/client_table_columns_name.go
  pkg/constant/undo.go
  pkg/datasource/sql/at.go
  pkg/datasource/sql/db.go
  pkg/datasource/sql/tx.go
  pkg/datasource/sql/undo/base/undo.go
  pkg/datasource/sql/undo/mysql/undo.go
  pkg/datasource/sql/undo/undo.go
  pkg/datasource/sql/undo_test.go
  pkg/rm/rm_api_test.go
  sample/tcc/grpc/pb/tcc_grpc.pb.go
  testdata/mock_tcc.go
Labels: coding, sample, rm, common

#243 frature: add update sql parser
  pkg/datasource/sql/exec/hook/basic_undo_builder.go
  pkg/datasource/sql/exec/hook/basic_undo_builder_test.go
Labels: coding

#254 add license github action
  .github/workflows/license.yml
  .licenserc.yaml
  goimports.sh
  pkg/common/bytes/buf_helper_test.go
  pkg/common/bytes/buf_test.go
  pkg/datasource/sql/parser/executortype_string.go
  pkg/datasource/sql/types/dbtype_string.go
  pkg/datasource/sql/types/sqltype_string.go
  pkg/rm/rm_api_test.go
  pkg/rm/rm_cache_test.go
  pkg/rm/rm_remoting_test.go
Labels: coding, rm, common, ci/cd

#264 frature: add update sql parser and remove tidb parser
  go.mod
  go.sum
  pkg/datasource/sql/exec/hook/basic_undo_builder.go
  pkg/datasource/sql/parser/parser_factory.go
Labels: coding

#263 fix ci failed because mock is invalid
  pkg/rm/tcc/tcc_service_test.go
Labels: coding, rm

#261 optimize: nested loop retries
  pkg/tm/transaction_executor.go
Labels: coding, tm

#280 feat: add http tcc
  .github/workflows/build.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/license.yml
  .golangci.yml
  go.mod
  go.sum
  pkg/integration/gin/gin_transaction_middleware.go
  pkg/integration/grpc/grpc_transaction_interceptor.go
  sample/tcc/gin/README.md
  sample/tcc/gin/client/main.go
  sample/tcc/gin/server/main.go
  sample/tcc/gin/server/service.go
Labels: coding, sample, integration, ci/cd

#284 feat: optimize retry
  pkg/tm/global_transaction.go
  pkg/util/backoff/backoff.go
  pkg/util/backoff/backoff_test.go
Labels: coding, tm

#286 Split client.Init into rm.Init and tm.Init methods
  pkg/rm/init.go
  pkg/tm/init.go
Labels: coding, rm, tm

#281 optimize: optimize global transaction usage
  go.sum
  pkg/tm/transaction_executor.go
  pkg/tm/transaction_executor_test.go
  sample/tcc/dubbo/client/cmd/client.go
  sample/tcc/fence/cmd/main.go
  sample/tcc/gin/client/main.go
  sample/tcc/grpc/cmd/client/main.go
  sample/tcc/local/cmd/local.go
  sample/tcc/local/service/service.go
Labels: coding, sample, tm
