Repository apache/incubator-seata-go, pull requests merged in 2023-03, with the labels that each got.

#477 feat(undo): add the use of undo log serialization
  pkg/datasource/sql/undo/base/undo.go
  pkg/datasource/sql/undo/parser/const.go
  pkg/datasource/sql/undo/parser/parser_api.go
  pkg/datasource/sql/undo/parser/parser_cache.go
  pkg/datasource/sql/undo/parser/parser_cache_test.go
  pkg/datasource/sql/undo/parser/parser_jackson.go
  pkg/datasource/sql/undo/parser/parser_jackson_test.go
  pkg/datasource/sql/undo/undo.go
  pkg/util/collection/collection.go
Labels: coding

#487 fix at bug
  pkg/datasource/sql/exec/at/multi_executor.go
  pkg/datasource/sql/undo/base/undo.go
  pkg/datasource/sql/util/sql.go
Labels: coding

#491 fix select for update bug
  pkg/datasource/sql/at.go
  pkg/datasource/sql/conn_at.go
  pkg/datasource/sql/exec/at/multi_update_excutor.go
  pkg/datasource/sql/exec/at/multi_update_excutor_test.go
  pkg/datasource/sql/exec/at/select_for_update_executor.go
  pkg/datasource/sql/exec/select_for_update_executor.go
  pkg/datasource/sql/types/types.go
  pkg/protocol/codec/codec.go
  pkg/protocol/codec/global_lock_query_req_codec.go
  pkg/protocol/codec/global_lock_query_req_codec_test.go
  pkg/protocol/codec/global_lock_query_resp_codec.go
  pkg/protocol/codec/global_lock_query_resp_codec_test.go
  pkg/rm/rm_remoting.go
Labels: coding, protocol, rm

#495 fix undo log sql type bug
  pkg/datasource/sql/conn_at.go
  pkg/datasource/sql/exec/at/at_executor.go
  pkg/datasource/sql/exec/at/base_executor.go
  pkg/datasource/sql/exec/at/delete_executor.go
  pkg/datasource/sql/exec/at/insert_executor.go
  pkg/datasource/sql/exec/at/insert_on_update_executor.go
  pkg/datasource/sql/exec/at/multi_delete_executor.go
  pkg/datasource/sql/exec/at/multi_update_excutor.go
  pkg/datasource/sql/exec/at/update_executor.go
  pkg/datasource/sql/parser/parser_factory.go
  pkg/datasource/sql/types/sql.go
  pkg/datasource/sql/undo/base/undo.go
Labels: coding

#505 Optimize multi delete of multi executor
  pkg/datasource/sql/exec/at/insert_on_update_executor.go
  pkg/datasource/sql/exec/at/multi_delete_executor.go
  pkg/datasource/sql/exec/at/multi_delete_executor_test.go
  pkg/datasource/sql/exec/at/multi_executor.go
  pkg/datasource/sql/parser/parse_factory_test.go
  pkg/datasource/sql/tx.go
  pkg/datasource/sql/types/executor.go
Labels: coding

#507 optimize multi update executor
  pkg/datasource/sql/exec/at/multi_update_excutor.go
  pkg/datasource/sql/undo/executor/executor.go
Labels: coding

#489 doc: add v1.0.4 change log
  changes/1.1.0.md
  changes/1.1.0_zh.md
Labels: milestone

#510 update 1.1.0 change log
  changes/1.1.0.md
  changes/1.1.0_zh.md
Labels: milestone

#509 optimize insert on update executor
  pkg/datasource/sql/datasource/utils.go
  pkg/datasource/sql/exec/at/insert_on_update_executor.go
  pkg/datasource/sql/undo/executor/executor.go
  pkg/datasource/sql/undo/executor/utils.go
Labels: coding

#512 update change log of v1.1.0
  changes/1.1.0.md
  changes/1.1.0_zh.md
Labels: milestone

#497 fix buildLockKey failed
  pkg/datasource/sql/exec/at/select_for_update_executor_test.go
  pkg/datasource/sql/types/meta.go
Labels: coding

#467 feat: add xa
  pkg/client/client.go
  pkg/client/config.go
  pkg/datasource/init.go
  pkg/datasource/sql/at_resource_manager.go
  pkg/datasource/sql/conn.go
  pkg/datasource/sql/conn/resource_xa.go
  pkg/datasource/sql/conn_at.go
  pkg/datasource/sql/conn_at_test.go
  pkg/datasource/sql/conn_xa.go
  pkg/datasource/sql/conn_xa_test.go
  pkg/datasource/sql/connector.go
  pkg/datasource/sql/connector_test.go
  pkg/datasource/sql/datasource/datasource_manager.go
  pkg/datasource/sql/datasource_resource.go
  pkg/datasource/sql/db.go
  pkg/datasource/sql/driver.go
  pkg/datasource/sql/driver_test.go
  pkg/datasource/sql/exec/at/insert_executor.go
  pkg/datasource/sql/exec/executor.go
  pkg/datasource/sql/exec/resource_xa.go
  pkg/datasource/sql/exec/select_for_update_executor.go
  pkg/datasource/sql/exec/xa/default.go
  pkg/datasource/sql/exec/xa/executor_xa.go
  pkg/datasource/sql/mock/mock_datasource_manager.go
  pkg/datasource/sql/plugin.go
  pkg/datasource/sql/root_context.go
  pkg/datasource/sql/tx.go
  pkg/datasource/sql/tx_at.go
  pkg/datasource/sql/tx_xa.go
  pkg/datasource/sql/types/types.go
  pkg/datasource/sql/util/convert.go
  pkg/datasource/sql/util/convert_test.go
  pkg/datasource/sql/xa/mysql_xa_connection.go
  pkg/datasource/sql/xa/mysql_xa_connection_test.go
  pkg/datasource/sql/xa/oracle_xa_connection.go
  pkg/datasource/sql/xa/oracle_xa_connection_test.go
  pkg/datasource/sql/xa/xa_connection_proxy.go
  pkg/datasource/sql/xa/xa_resource.go
  pkg/datasource/sql/xa/xa_resource_factory.go
  pkg/datasource/sql/xa_branch_xid.go
  pkg/datasource/sql/xa_branch_xid_test.go
  pkg/datasource/sql/xa_resource_manager.go
  pkg/datasource/sql/xa_xid.go
  pkg/datasource/sql/xa_xid_builder.go
  pkg/protocol/branch/branch.go
  pkg/rm/rm_api.go
Labels: coding, protocol, rm

#525 optimize(undo): change default parser name to json from jackson
  pkg/datasource/sql/undo/parser/const.go
  pkg/datasource/sql/undo/parser/parser_cache.go
  pkg/datasource/sql/undo/parser/parser_cache_test.go
  pkg/datasource/sql/undo/parser/parser_json.go
  pkg/datasource/sql/undo/parser/parser_json_test.go
Labels: coding

#420 feat(fence): implement fence use datasource proxy
  go.mod
  go.sum
  pkg/rm/tcc/fence/fence_api.go
  pkg/rm/tcc/fence/fence_driver.go
  pkg/rm/tcc/fence/fence_driver_conn.go
  pkg/rm/tcc/fence/fence_driver_conn_test.go
  pkg/rm/tcc/fence/fence_driver_tx.go
  pkg/rm/tcc/fence/fennce_driver_test.go
  pkg/rm/tcc/fence/handler/tcc_fence_wrapper_handler.go
  pkg/tm/context.go
Labels: coding, rm, tm

#532 fix: remove duplicate code
  pkg/datasource/sql/conn_xa.go
Labels: coding
