Repository apache/incubator-seata-go, pull requests merged in 2023-05, with the labels that each got.

#535 Ftr:integrate test
  .github/workflows/integrate-test.yml
  integrate_test.sh
Labels: ci/cd

#545 fix get db version bug
  pkg/datasource/sql/connector.go
Labels: coding

#547 fix xa start bug
  pkg/datasource/sql/xa/mysql_xa_connection.go
Labels: coding

#548 feat: :sparkles: fix
  pkg/datasource/sql/xa/mysql_xa_connection.go
Labels: coding

#554 perf: optimize the performance of XA transactions
  pkg/datasource/sql/connector.go
  pkg/datasource/sql/db.go
  pkg/datasource/sql/driver.go
  pkg/rm/tcc/fence/fence_driver_tx.go
  pkg/rm/tcc/fence/fennce_driver_test.go
Labels: coding, rm

#557 fix: fix xa bug
  pkg/datasource/sql/conn_xa.go
  pkg/datasource/sql/xa/mysql_xa_connection.go
  pkg/datasource/sql/xa_resource_manager.go
Labels: coding

#561 Fix xa bug12
  pkg/datasource/sql/db.go
  pkg/datasource/sql/xa_resource_manager.go
  pkg/remoting/processor/client/rm_branch_commit_processor.go
  pkg/tm/transaction_executor.go
Labels: coding, remoting, tm

#562 feat: fix bug
  pkg/datasource/sql/conn.go
  pkg/datasource/sql/conn_xa.go
Labels: coding

#563 Fix/fix xa bug2
  pkg/datasource/sql/conn.go
  pkg/datasource/sql/conn_xa.go
Labels: coding

#564 fix xa branch commit bug
  goimports.sh
  pkg/client/client.go
  pkg/datasource/sql/conn_xa.go
  pkg/datasource/sql/db.go
  pkg/datasource/sql/driver.go
  pkg/datasource/sql/exec/at/multi_delete_executor.go
  pkg/datasource/sql/xa/mysql_xa_connection.go
Labels: coding

#550 add change-log of version 1.1.1
  changes/1.1.1.md
  changes/1.1.1_zh.md
Labels: milestone

#566 feat: fix xa local bug
  pkg/datasource/sql/conn_xa.go
  pkg/datasource/sql/xa/mysql_xa_connection_test.go
Labels: coding

#567 add 1.2.0 change log
  changes/1.2.0.md
  changes/1.2.0_zh.md
Labels: milestone
