Repository apache/incubator-seata-go, pull requests merged in 2023-02, with the labels that each got.

#459 fix rollback error log
  pkg/datasource/sql/conn_at.go
Labels: coding

#466 fix: fix some typo
  pkg/datasource/sql/exec/at/at_executor.go
  pkg/datasource/sql/exec/at/base_executor.go
  pkg/datasource/sql/exec/at/delete_executor.go
  pkg/datasource/sql/exec/at/insert_executor.go
  pkg/datasource/sql/exec/at/plain_executor.go
  pkg/datasource/sql/exec/at/plain_executor_test.go
  pkg/datasource/sql/exec/at/update_executor.go
Labels: coding

#433 feat: XA connect manager
  go.mod
  go.sum
  pkg/datasource/sql/conn.go
  pkg/datasource/sql/datasource_resource.go
  pkg/datasource/sql/root_context.go
  pkg/datasource/sql/xa/xa_connection.go
  pkg/datasource/sql/xa/xa_connection_proxy.go
Labels: coding

#391 [WIP]feat: support xa oracle connection
  go.mod
  go.sum
  pkg/datasource/sql/conn/oracle.go
  pkg/datasource/sql/conn/oracle_test.go
  pkg/datasource/sql/conn/resource_xa.go
Labels: coding

#470 sample/migrate
  README.md
  README_ZH.md
  go.mod
  go.sum
  pkg/rm/tcc/tcc_service_test.go
  pkg/rm/two_phase_test.go
  sample/at/basic/main.go
  sample/at/basic/service.go
  sample/at/gin/client/main.go
  sample/at/gin/server/main.go
  sample/at/gin/server/service.go
  sample/at/non_transaction/main.go
  sample/at/non_transaction/service.go
  sample/at/rollback/client/main.go
  sample/at/rollback/rollback.sql
  sample/at/rollback/server/main.go
  sample/at/rollback/server/service.go
  sample/at/rollback/server2/main.go
  sample/at/rollback/server2/service.go
  sample/conf/seatago.yml
  sample/dockercompose/docker-compose.yml
  sample/dockercompose/docker-health-check.sh
  sample/dockercompose/mysql/mysqld.cnf
  sample/dockercompose/mysql/order.sql
  sample/tcc/dubbo/client/cmd/client.go
  sample/tcc/dubbo/client/conf/dubbogo.yml
  sample/tcc/dubbo/client/service/user_provider.go
  sample/tcc/dubbo/server/cmd/server.go
  sample/tcc/dubbo/server/conf/dubbogo.yml
  sample/tcc/dubbo/server/service/user_provider.go
  sample/tcc/fence/README_ZH.md
  sample/tcc/fence/cmd/main.go
  sample/tcc/fence/script/mysql.sql
  sample/tcc/fence/script/oracle.sql
  sample/tcc/fence/script/postgresql.sql
  sample/tcc/fence/service/service.go
  sample/tcc/gin/README.md
  sample/tcc/gin/client/main.go
  sample/tcc/gin/server/main.go
  sample/tcc/gin/server/service.go
  sample/tcc/grpc/cmd/client/main.go
  sample/tcc/grpc/cmd/server/main.go
  sample/tcc/grpc/pb/tcc_grpc.pb.go
  sample/tcc/grpc/pb/tcc_grpc.proto
  sample/tcc/grpc/pb/tcc_grpc_grpc.pb.go
  sample/tcc/grpc/service/service.go
  sample/tcc/local/cmd/local.go
  sample/tcc/local/service/service.go
  sample/tcc/propagation/README_ZH.md
  sample/tcc/propagation/first/main.go
  sample/tcc/propagation/second/main.go
  sample/tcc/propagation/tc_log.png
Labels: coding, sample, rm

#472 fix(tm): fix missing value of context
  pkg/tm/transaction_executor.go
  pkg/tm/transaction_executor_test.go
Labels: coding, tm

#456 refactor(datasource,rm): insert on update executor
  pkg/datasource/sql/conn/oracle_test.go
  pkg/datasource/sql/exec/at/at_executor.go
  pkg/datasource/sql/exec/at/insert_executor.go
  pkg/datasource/sql/exec/at/insert_executor_test.go
  pkg/datasource/sql/exec/at/insert_on_update_executor.go
  pkg/datasource/sql/exec/at/insert_on_update_executor_test.go
  pkg/datasource/sql/parser/parser_factory.go
  pkg/datasource/sql/tx_at.go
  pkg/datasource/sql/types/sql.go
  pkg/datasource/sql/types/sqltype_string.go
  pkg/rm/tcc/fence/handler/tcc_fence_wrapper_handler.go
  pkg/rm/tcc/tcc_service_test.go
Labels: coding, rm

#453 optimize MessageType and TransactionErrorCode
  pkg/protocol/message/constant.go
Labels: coding, protocol

#481 reactor:multiple update executor
  pkg/datasource/sql/exec/at/at_executor.go
  pkg/datasource/sql/exec/at/multi_executor.go
  pkg/datasource/sql/exec/at/multi_executor_test.go
  pkg/datasource/sql/exec/at/multi_update_excutor.go
  pkg/datasource/sql/exec/at/multi_update_excutor_test.go
Labels: coding
