Repository apache/incubator-seata-go, pull requests merged in 2023-12, with the labels that each got.

#621 ci: add codeql
  .github/workflows/codeql.yml
Labels: ci/cd

#635 feature: init saga framework
  pkg/saga/readme.md
  pkg/saga/statemachine/engine/contant.go
  pkg/saga/statemachine/engine/events/event.go
  pkg/saga/statemachine/engine/events/event_bus.go
  pkg/saga/statemachine/engine/events/event_consumer.go
  pkg/saga/statemachine/engine/events/event_publisher.go
  pkg/saga/statemachine/engine/expr/expression.go
  pkg/saga/statemachine/engine/invoker/invoker.go
  pkg/saga/statemachine/engine/process_ctrl/bussiness_processor.go
  pkg/saga/statemachine/engine/process_ctrl/instruction/instruction.go
  pkg/saga/statemachine/engine/process_ctrl/process_context.go
  pkg/saga/statemachine/engine/process_ctrl/process_type.go
  pkg/saga/statemachine/engine/process_ctrl/statemachine_processor.go
  pkg/saga/statemachine/engine/process_ctrl_statemachine_engine.go
  pkg/saga/statemachine/engine/sequence/sequence.go
  pkg/saga/statemachine/engine/sequence/uuid.go
  pkg/saga/statemachine/engine/statemachine_config.go
  pkg/saga/statemachine/engine/statemachine_engine.go
  pkg/saga/statemachine/engine/status_decision/status_decision.go
  pkg/saga/statemachine/engine/store/statemachine_store.go
  pkg/saga/statemachine/statelang/parser/choice_state_json_parser.go
  pkg/saga/statemachine/statelang/parser/statemachine_json_parser.go
  pkg/saga/statemachine/statelang/parser/statemachine_json_parser_test.go
  pkg/saga/statemachine/statelang/parser/statemachine_parser.go
  pkg/saga/statemachine/statelang/state.go
  pkg/saga/statemachine/statelang/state/choice_state.go
  pkg/saga/statemachine/statelang/state/task_state.go
  pkg/saga/statemachine/statelang/state_instance.go
  pkg/saga/statemachine/statelang/statemachine.go
  pkg/saga/statemachine/statelang/statemachine_instance.go
  pkg/util/reflectx/unmarkshaler.go
Labels: coding

#622 feat: add round robin in remote module
  pkg/remoting/loadbalance/loadbalance.go
  pkg/remoting/loadbalance/round_robin_loadbalance.go
  pkg/remoting/loadbalance/round_robin_loadbalance_test.go
Labels: coding, remoting
