Repository apache/incubator-seata-go, pull requests merged in 2024-12, with the labels that each got.

#691 feature:add undo protobuf parser
  pkg/datasource/sql/undo/parser/branch_undo_log.pb.go
  pkg/datasource/sql/undo/parser/branch_undo_log.proto
  pkg/datasource/sql/undo/parser/parser_cache.go
  pkg/datasource/sql/undo/parser/parser_json_test.go
  pkg/datasource/sql/undo/parser/parser_protobuf.go
  pkg/datasource/sql/undo/parser/parser_protobuf_test.go
Labels: coding

#724 fix: undo log sql
  pkg/datasource/sql/undo/builder/basic_undo_log_builder.go
  pkg/datasource/sql/undo/builder/mysql_update_undo_log_builder_test.go
Labels: coding

#686 feat:add more linter in configuration file
  .golangci.yml
  go.mod
  go.sum
  pkg/datasource/sql/datasource/mysql/trigger.go
  pkg/datasource/sql/undo/base/undo.go
  pkg/datasource/sql/undo/executor/executor.go
  pkg/rm/rm_remoting.go
  pkg/rm/tcc/fence/fennce_driver_test.go
  pkg/rm/tcc/tcc_service.go
Labels: module/rm, coding, rm

#736 fix:sql statement was not closed
  .golangci.yml
  pkg/datasource/sql/datasource/mysql/trigger.go
  pkg/datasource/sql/exec/at/escape.go
  pkg/datasource/sql/tx.go
  pkg/datasource/sql/types/image.go
  pkg/datasource/sql/undo/base/undo.go
  pkg/datasource/sql/undo/executor/executor.go
  pkg/datasource/sql/undo/executor/mysql_undo_delete_executor.go
  pkg/datasource/sql/undo/executor/mysql_undo_insert_executor.go
  pkg/datasource/sql/undo/executor/mysql_undo_update_executor.go
  pkg/datasource/sql/undo/executor/sql.go
  pkg/remoting/getty/readwriter.go
  pkg/remoting/loadbalance/loadbalance.go
Labels: coding, remoting

#738 feat: remove session when send heart beat message failed
  pkg/remoting/getty/listener.go
Labels: coding, remoting

#727 fix: bypassing modifying the primary key
  pkg/datasource/sql/undo/builder/mysql_insertonduplicate_update_undo_log_builder.go
  pkg/datasource/sql/undo/builder/mysql_insertonduplicate_update_undo_log_builder_test.go
Labels: coding

#719 only inserted fields
  pkg/datasource/sql/exec/at/base_executor.go
  pkg/datasource/sql/exec/at/insert_executor.go
  pkg/datasource/sql/exec/at/insert_executor_test.go
Labels: coding

#746 refactor getty module
  pkg/client/client.go
  pkg/remoting/config/config.go
  pkg/remoting/getty/getty_client.go
  pkg/remoting/getty/getty_client_test.go
  pkg/remoting/getty/getty_init.go
  pkg/remoting/getty/getty_remoting.go
  pkg/remoting/getty/getty_remoting_test.go
  pkg/remoting/getty/listener.go
  pkg/remoting/getty/rpc_client.go
  pkg/remoting/getty/session_manager.go
  pkg/remoting/processor/client/client_on_response_processor.go
Labels: coding, remoting

#744 feat: add func invoker
  pkg/saga/statemachine/engine/invoker/func_invoker.go
  pkg/saga/statemachine/engine/invoker/func_invoker_test.go
Labels: coding

#665 fix:Reclaim the heartbeat response message to avoid memory leakage of GettyRemoting.futures
  pkg/remoting/processor/client/client_heart_beat_processon.go
Labels: coding, remoting

#749 fix: fix heart beat bug
  pkg/remoting/processor/client/client_heart_beat_processon.go
Labels: coding, remoting

#739 feat: Implement automatic refresh functionality for TableMetaCache
  pkg/datasource/sql/datasource/base/meta_cache.go
  pkg/datasource/sql/datasource/base/meta_cache_test.go
  pkg/datasource/sql/datasource/mysql/meta_cache.go
  pkg/datasource/sql/datasource/mysql/trigger.go
  pkg/datasource/sql/datasource/mysql/trigger_test.go
  pkg/datasource/sql/driver.go
  pkg/datasource/sql/exec/at/insert_executor_test.go
  pkg/datasource/sql/exec/at/multi_update_excutor_test.go
  pkg/datasource/sql/exec/at/update_executor_test.go
  testdata/meta_cache.go
Labels: coding

#714 optimize: optimize the speed of buildLockKey
  pkg/datasource/sql/undo/builder/basic_undo_log_builder.go
  pkg/datasource/sql/undo/builder/basic_undo_log_builder_test.go
Labels: coding

#717 【WIP】fix: xa report state to TC
  pkg/datasource/sql/conn_xa.go
Labels: coding
