Repository apache/incubator-seata-go, pull requests merged in 2024-02, with the labels that each got.

#659 add undo compressor log support
  pkg/compressor/compressor_factory.go
  pkg/compressor/compressor_type.go
  pkg/compressor/compressor_type_test.go
  pkg/datasource/sql/undo/base/undo.go
  pkg/datasource/sql/undo/config.go
Labels: coding

#650 feature: add serverice task parse in statelang
  pkg/saga/statemachine/constant/constant.go
  pkg/saga/statemachine/constant/contant.go
  pkg/saga/statemachine/statelang/parser/choice_state_json_parser.go
  pkg/saga/statemachine/statelang/parser/compensation_trigger_state_parser.go
  pkg/saga/statemachine/statelang/parser/end_state_parser.go
  pkg/saga/statemachine/statelang/parser/statemachine_json_parser.go
  pkg/saga/statemachine/statelang/parser/statemachine_json_parser_test.go
  pkg/saga/statemachine/statelang/parser/statemachine_parser.go
  pkg/saga/statemachine/statelang/parser/sub_state_machine_parser.go
  pkg/saga/statemachine/statelang/parser/task_state_json_parser.go
  pkg/saga/statemachine/statelang/state.go
  pkg/saga/statemachine/statelang/state/choice_state.go
  pkg/saga/statemachine/statelang/state/compensation_trigger_state.go
  pkg/saga/statemachine/statelang/state/end_state.go
  pkg/saga/statemachine/statelang/state/sub_state_machine.go
  pkg/saga/statemachine/statelang/state/task_state.go
  testdata/saga/statelang/simple_statelang_with_choice.json
  testdata/saga/statelang/simple_statemachine.json
  testdata/saga/statelang/state_machine_new_designer.json
Labels: coding

#595 bugfix: fix return of Commit and Rollback
  pkg/tm/global_transaction.go
Labels: coding, tm

#612 fix issue 609,610,611
  pkg/datasource/sql/conn_at.go
  pkg/datasource/sql/datasource/base/meta_cache.go
  pkg/datasource/sql/exec/at/select_for_update_executor.go
Labels: coding

#605 【等CI结束就合并】feat: Implement the discovery service by Etcd
  go.mod
  go.sum
  pkg/discovery/etcd3.go
  pkg/discovery/etcd3_test.go
  pkg/discovery/init.go
  pkg/discovery/init_test.go
  pkg/discovery/mock/mock_etcd_client.go
  pkg/discovery/mock/test_etcd_client.go
Labels: coding

#649 feature: add saga persistence layer
  go.mod
  go.sum
  pkg/remoting/loadbalance/loadbalance.go
  pkg/remoting/loadbalance/round_robin_loadbalance.go
  pkg/remoting/loadbalance/round_robin_loadbalance_test.go
  pkg/saga/statemachine/constant/constant.go
  pkg/saga/statemachine/engine/process_ctrl/process_context.go
  pkg/saga/statemachine/engine/serializer/serializer.go
  pkg/saga/statemachine/engine/serializer/serializer_test.go
  pkg/saga/statemachine/engine/store/db/db.go
  pkg/saga/statemachine/engine/store/db/db_test.go
  pkg/saga/statemachine/engine/store/db/statelang.go
  pkg/saga/statemachine/engine/store/db/statelang_test.go
  pkg/saga/statemachine/engine/store/db/statelog.go
  pkg/saga/statemachine/engine/store/db/statelog_test.go
  pkg/saga/statemachine/engine/store/statemachine_store.go
  pkg/saga/statemachine/engine/utils.go
  pkg/saga/statemachine/statelang/state_instance.go
  pkg/saga/statemachine/statelang/statemachine_instance.go
  testdata/sql/saga/sqlite_init.sql
Labels: coding, remoting

#668 feat: add grpc invoker in saga mode
  go.mod
  pkg/saga/statemachine/engine/invoker/grpc_invoker.go
  pkg/saga/statemachine/engine/invoker/grpc_invoker_test.go
  pkg/saga/statemachine/engine/invoker/invoker.go
  pkg/saga/statemachine/statelang/parser/statemachine_parser.go
  pkg/saga/statemachine/statelang/parser/task_state_json_parser.go
  pkg/saga/statemachine/statelang/state/task_state.go
  testdata/saga/engine/invoker/grpc/product.go
  testdata/saga/engine/invoker/grpc/product.pb.go
  testdata/saga/engine/invoker/grpc/product.proto
  testdata/saga/engine/invoker/grpc/product_grpc.pb.go
Labels: coding
