Repository apache/incubator-seata-go, pull requests merged in 2025-08, with the labels that each got.

#868 Feature/add script manager&actuator
  go.mod
  go.sum
  pkg/saga/statemachine/engine/config/default_statemachine_config.go
  pkg/saga/statemachine/engine/invoker/invoker.go
  pkg/saga/statemachine/engine/invoker/javascript_script_invoker.go
  pkg/saga/statemachine/engine/invoker/javascript_script_invoker_test.go
  pkg/saga/statemachine/engine/invoker/local_invoker.go
  pkg/saga/statemachine/engine/invoker/local_invoker_test.go
Labels: coding

#835 fix: re-enabled integration test action
  .github/workflows/integrate-test.yml
Labels: bug, ci/cd, module/at

#828 handle Unexpected transaction rollback
  pkg/datasource/sql/undo/base/undo.go
  pkg/datasource/sql/undo/executor/executor.go
  pkg/datasource/sql/undo/executor/executor_test.go
  pkg/util/errors/code.go
  pkg/util/errors/error_code_test.go
Labels: coding

#855 Implement SagaResource and SagaResourceManager
  pkg/client/client.go
  pkg/saga/rm/handler_saga.go
  pkg/saga/rm/saga_resource.go
  pkg/saga/rm/saga_resource_manager.go
  pkg/saga/rm/saga_resource_manager_test.go
  pkg/saga/rm/state_machine_engine_holder.go
  pkg/saga/statemachine/engine/exception/exception.go
  pkg/saga/statemachine/engine/exception/exception_test.go
  pkg/saga/statemachine/engine/exception/forward_invalid_exception.go
  pkg/saga/statemachine/engine/exception/forward_invalid_exception_test.go
  pkg/saga/tm/default_saga_transactional_template.go
Labels: module/saga, coding

#849 fix:The WithGlobalTx method returns the exception caught by recover
  pkg/tm/transaction_executor.go
  pkg/tm/transaction_executor_test.go
Labels: bug, coding, tm

#874 fix: Fix GetScanSlice not handling all column types in AT mode
  pkg/datasource/sql/datasource/utils.go
  pkg/datasource/sql/datasource/utils_test.go
Labels: bug, module/at, coding, first-time contributor
