Repository apache/incubator-seata-go, pull requests merged in 2025-06, with the labels that each got.

#824 refactor: update SHA256 checksum command in makefile for cross-platfo…
  makefile
Labels: refactor, module/at

#838 refactor-engine/core
  pkg/saga/statemachine/engine/config/default_statemachine_config.go
  pkg/saga/statemachine/engine/core/process_ctrl_statemachine_engine.go
  pkg/saga/statemachine/engine/pcext/compensation_holder.go
  pkg/saga/statemachine/engine/pcext/engine_utils.go
  pkg/saga/statemachine/engine/pcext/instruction.go
  pkg/saga/statemachine/engine/pcext/loop_context_holder.go
  pkg/saga/statemachine/engine/pcext/loop_task_utils.go
  pkg/saga/statemachine/engine/pcext/parameter_utils.go
  pkg/saga/statemachine/engine/pcext/process_handler.go
  pkg/saga/statemachine/engine/pcext/process_router.go
  pkg/saga/statemachine/engine/pcext/state_router_impl.go
  pkg/saga/statemachine/engine/repo/repository/state_log_repository.go
  pkg/saga/statemachine/engine/repo/repository/state_machine_repository.go
  pkg/saga/statemachine/engine/repo/repository/state_machine_repository_test.go
  pkg/saga/statemachine/engine/repo/statemachine_store.go
  pkg/saga/statemachine/engine/statemachine_config.go
  pkg/saga/statemachine/engine/statemachine_engine.go
  pkg/saga/statemachine/engine/statemachine_engine_test.go
  pkg/saga/statemachine/engine/strategy.go
  pkg/saga/statemachine/engine/strategy/status_decision.go
  pkg/saga/statemachine/engine/utils/process_context_utils.go
  pkg/saga/statemachine/process_ctrl/bussiness_processor.go
  pkg/saga/statemachine/process_ctrl/default_process_handler.go
  pkg/saga/statemachine/process_ctrl/event.go
  pkg/saga/statemachine/process_ctrl/event_bus.go
  pkg/saga/statemachine/process_ctrl/event_consumer.go
  pkg/saga/statemachine/process_ctrl/event_publisher.go
  pkg/saga/statemachine/process_ctrl/handlers/service_task_state_handler.go
  pkg/saga/statemachine/process_ctrl/instruction.go
  pkg/saga/statemachine/process_ctrl/process_context.go
  pkg/saga/statemachine/process_ctrl/process_controller.go
  pkg/saga/statemachine/process_ctrl/process_router.go
  pkg/saga/statemachine/store/db/statelog.go
  pkg/saga/statemachine/store/db/statelog_test.go
  pkg/saga/statemachine/store/store.go
Labels: module/saga, coding

#772 fix: Solve the conflict problem of introducing multiple versions of knadh
  .github/workflows/golangci-lint.yml
  go.mod
  pkg/client/config.go
Labels: bug, ci/cd, coding

#839 fix action errors
  .github/workflows/build.yml
  pkg/datasource/sql/datasource/base/meta_cache_test.go
Labels: bug, ci/cd, coding
