Repository apache/incubator-seata-go, pull requests merged in 2025-05, with the labels that each got.

#802 support get db version in conn
  pkg/datasource/sql/conn.go
  pkg/datasource/sql/conn_at.go
  pkg/datasource/sql/types/types.go
Labels: coding

#778 Feature/saga interface optimization
  pkg/saga/statemachine/constant/constant.go
  pkg/saga/statemachine/engine/core/process_ctrl_statemachine_engine.go
  pkg/saga/statemachine/engine/core/statemachine_engine.go
  pkg/saga/statemachine/engine/core/utils.go
  pkg/util/errors/code.go
Labels: module/saga, coding

#808 refactor: implement pending TODOs in machine status_decision logic
  pkg/saga/statemachine/constant/constant.go
  pkg/saga/statemachine/engine/core/engine_utils.go
  pkg/saga/statemachine/engine/core/status_decision.go
  pkg/saga/statemachine/engine/exception/exception.go
Labels: coding

#786 support ipv6
  pkg/discovery/etcd3.go
  pkg/discovery/etcd3_test.go
  pkg/discovery/file.go
  pkg/discovery/file_test.go
  pkg/remoting/getty/session_manager.go
  pkg/remoting/loadbalance/xid_loadbalance.go
  pkg/remoting/loadbalance/xid_loadbalance_test.go
  pkg/util/net/address_validator.go
  pkg/util/net/address_validator_test.go
Labels: coding, remoting

#777 optimize: optimize transaction timeout judgment
  pkg/tm/context.go
  pkg/tm/global_transaction.go
  pkg/tm/transaction_executor.go
  pkg/tm/transaction_executor_test.go
Labels: coding, tm

#813 optimize: add some licenser header
  .gitignore
  .licenserc.yaml
  CONTRIBUTING_CN.md
  README_ZH.md
  testdata/sql/undo_log.sql
Labels: documentation, enhancement

#810 fix: when using queryContext, it will cause the transaction to fail
  pkg/datasource/sql/conn_at.go
Labels: bug, coding

#821 bugfix：Remove issue translation workflow as usthe/issues-translate-action@v2.7 does not allow issues in apache/incubator-seata-go
  .github/workflows/issue-robot.yml
Labels: ci/cd

#820 Fix: HTTP/2 CONTINUATION flood vulnerability (GO-2024-2687)
  go.mod
  go.sum
Labels: bug, module/at, coding

#822 Revert "bugfix：Remove issue translation workflow as usthe/issues-translate-action@v2.7 does not allow issues in apache/incubator-seata-go"
  .github/workflows/issue-robot.yml
Labels: ci/cd

#823 bugfix: Remove issue translation workflow as usthe/issues-translate-a…
  .github/workflows/issue-robot.yml
Labels: bug, ci/cd, refactor, module/at
