Repository apache/incubator-seata-go, pull requests merged in 2025-04, with the labels that each got.

#797 optimize: add ASF header to some files
  CONTRIBUTING.md
  README.md
  changes/2.0.0.md
  changes/2.0.0_zh.md
  pkg/datasource/sql/mock/README.md
  pkg/datasource/sql/undo/parser/branch_undo_log.pb.go
  pkg/discovery/mock/mock_etcd_client.go
Labels: coding, milestone

#771 fix: mysql insert on update duplicate sensitive case not matched (#700)
  pkg/datasource/sql/exec/at/insert_on_update_executor.go
  pkg/datasource/sql/exec/at/insert_on_update_executor_test.go
Labels: coding

#745 optimize : tccfence log table deleted should be optimized
  pkg/client/client.go
  pkg/client/config_test.go
  pkg/rm/tcc/fence/config/tcc_fence_config.go
  pkg/rm/tcc/fence/fence.go
  pkg/rm/tcc/fence/fennce_driver_test.go
  pkg/rm/tcc/fence/handler/tcc_fence_wrapper_handler.go
  pkg/rm/tcc/fence/store/db/dao/store_api.go
  pkg/rm/tcc/fence/store/db/dao/tcc_fence_db.go
  pkg/rm/tcc/fence/store/db/dao/tcc_fence_db_test.go
  pkg/rm/tcc/fence/store/db/model/tcc_fence_do.go
  pkg/rm/tcc/fence/store/db/sql/tcc_fence_store_sql.go
  pkg/rm/tcc/tcc_resource.go
  testdata/conf/seatago.yml
Labels: coding, rm

#806 feat:add label for pull request automatically (ci/cd)
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: ci/cd
